import React from "react";
import ReactDOM from "react-dom/client";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faBolt,
  faBookOpen,
  faCheckCircle,
  faCode,
  faComments,
  faDatabase,
  faDesktop,
  faDiagramProject,
  faDownload,
  faFileLines,
  faGraduationCap,
  faLaptopCode,
  faLayerGroup,
  faMoon,
  faPaperPlane,
  faPhone,
  faPlay,
  faRocket,
  faShieldHalved,
  faSitemap,
  faSpinner,
  faStar,
  faSun,
  faTabletScreenButton,
  faUserGraduate,
  faWandMagicSparkles,
  faXmark,
  faArrowRight,
  faArrowUp,
  faCircleChevronRight,
} from "@fortawesome/free-solid-svg-icons";
import {
  faCss3,
  faGithub,
  faHtml5,
  faInstagram,
  faReact,
  faNodeJs,
  faBootstrap,
  faJs,
  faPhp,
  faPython,
  faGitAlt,
} from "@fortawesome/free-brands-svg-icons";
import App from "./App";
import "./styles/global.css";
import "./styles/refined.css";

library.add(
  faBookOpen,
  faCheckCircle,
  faCode,
  faComments,
  faDatabase,
  faBolt,
  faDesktop,
  faDiagramProject,
  faDownload,
  faFileLines,
  faGraduationCap,
  faLaptopCode,
  faLayerGroup,
  faMoon,
  faPaperPlane,
  faPhone,
  faPlay,
  faRocket,
  faShieldHalved,
  faSitemap,
  faSpinner,
  faStar,
  faSun,
  faTabletScreenButton,
  faUserGraduate,
  faWandMagicSparkles,
  faXmark,
  faArrowRight,
  faArrowUp,
  faCircleChevronRight,
  faGithub,
  faHtml5,
  faCss3,
  faInstagram,
  faReact,
  faNodeJs,
  faBootstrap,
  faJs,
  faPhp,
  faPython,
  faGitAlt,
);

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
